import {
  ExamTarget,
  EvidenceItem,
  MaterialItem,
  AbilityBaseline,
  PublicResource,
  WeeklyPlan,
  DailyPlan,
  User,
  UserSettings,
} from "@/types";

// ==================== 当前用户 ====================

export const mockUser: User = {
  id: "u-001",
  name: "备考学员",
  avatar: undefined,
  role: "user",
  educationLevel: "middle",
  dailyAvailableTime: 180,
  studyReminderTime: "08:00",
  notificationSettings: {
    studyReminder: true,
    examUpdate: true,
    resourceUpdate: true,
    weeklyReport: true,
  },
  currentExamTargetId: "et-001",
  createdAt: "2026-09-25T08:00:00Z",
  updatedAt: "2026-10-01T08:00:00Z",
};

// ==================== 目标考试 ====================

export const mockExamTargets: ExamTarget[] = [
  {
    id: "et-001",
    userId: "u-001",
    name: "浙江省·杭州市 初中语文 公办学校招聘",
    region: "浙江省 · 杭州市",
    regionCode: "330100",
    province: "浙江省",
    city: "杭州市",
    examType: "public_school",
    educationLevel: "middle",
    year: 2026,
    batch: "上半年统招",
    subject: "chinese",
    stage: "preparation",
    status: "confirmed",
    targetStatus: "announcement",
    isCurrent: true,
    announcementUrl: "https://edu.hangzhou.gov.cn/art/2026/9/1/art_1228920387_58925199.html",
    createdAt: "2026-09-25T08:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
  },
  {
    id: "et-002",
    userId: "u-001",
    name: "江苏省·南京市 高中语文 事业单位招聘",
    region: "江苏省 · 南京市",
    regionCode: "320100",
    province: "江苏省",
    city: "南京市",
    examType: "public_institution",
    educationLevel: "high",
    year: 2025,
    batch: "下半年招聘",
    subject: "chinese",
    stage: "completed",
    status: "archived",
    targetStatus: "region",
    isCurrent: false,
    createdAt: "2025-03-10T08:00:00Z",
    updatedAt: "2025-09-01T08:00:00Z",
  },
  // —— 资料模块演示案例：无资料 ——（可在“我的考试”切换为当前目标体验）
  {
    id: "et-demo-mat-none",
    userId: "u-001",
    name: "【演示案例·还没有资料】浙江省·温州市 初中语文 公办学校招聘",
    region: "浙江省 · 温州市",
    regionCode: "330300",
    province: "浙江省",
    city: "温州市",
    examType: "public_school",
    educationLevel: "middle",
    year: 2026,
    batch: "提前批招聘",
    subject: "chinese",
    stage: "preparation",
    status: "confirmed",
    targetStatus: "announcement",
    isCurrent: false,
    createdAt: "2026-09-20T08:00:00Z",
    updatedAt: "2026-09-20T08:00:00Z",
  },
  // —— 资料模块演示案例：多套资料冲突 ——
  {
    id: "et-demo-mat-multi",
    userId: "u-001",
    name: "【演示案例·多套资料冲突】浙江省·宁波市 初中语文 公办学校招聘",
    region: "浙江省 · 宁波市",
    regionCode: "330200",
    province: "浙江省",
    city: "宁波市",
    examType: "public_school",
    educationLevel: "middle",
    year: 2026,
    batch: "上半年统招",
    subject: "chinese",
    stage: "preparation",
    status: "confirmed",
    targetStatus: "announcement",
    isCurrent: false,
    createdAt: "2026-09-22T08:00:00Z",
    updatedAt: "2026-09-22T08:00:00Z",
  },
];

// ==================== 考情证据（字段级结构化证据） ====================
//
// 种子数据模拟“真实后端中已完成人工审核”的状态：
// 只有 official 条目带 reviewerName/reviewedAt；
// 用户新提交公告提取出的结论永远不会自动变成 official。

const ET001_SCOPE = "浙江省杭州市 · 2026年上半年统招 · 初中语文";
const ET001_URL = "https://edu.hangzhou.gov.cn/art/2026/9/1/art_1228920387_58925199.html";

export const mockEvidenceItems: EvidenceItem[] = [
  {
    id: "ev-seed-001",
    examTargetId: "et-001",
    field: "subjects",
    value: "《教育综合知识》、《学科专业知识（初中语文）》",
    reviewStatus: "official",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "笔试科目为《教育综合知识》和《学科专业知识（初中语文）》。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-28T10:30:00Z",
    reviewerName: "考情审核员（模拟）",
    reviewedAt: "2026-09-28T10:30:00Z",
    version: 1,
  },
  {
    id: "ev-seed-002",
    examTargetId: "et-001",
    field: "exam_scope",
    value:
      "现代汉语基础知识；古代汉语（实词、虚词、句式）；文学常识与作品分析；语文课程标准与教学设计；写作与案例分析",
    reviewStatus: "official",
    sourceName: "杭州市教育局2026年考试大纲",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "学科专业知识考查现代汉语、古代汉语、文学常识、课程标准与教学设计等内容。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-28T14:00:00Z",
    reviewerName: "考情审核员（模拟）",
    reviewedAt: "2026-09-28T14:00:00Z",
    version: 1,
  },
  {
    id: "ev-seed-003",
    examTargetId: "et-001",
    field: "qualification",
    value: "本科及以上学历；具有相应学段教师资格证；年龄35周岁以下",
    reviewStatus: "official",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "报考人员须本科及以上学历，具有相应学段教师资格证，年龄35周岁以下。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-28T10:30:00Z",
    reviewerName: "考情审核员（模拟）",
    reviewedAt: "2026-09-28T10:30:00Z",
    version: 1,
  },
  {
    id: "ev-seed-004",
    examTargetId: "et-001",
    field: "registration_time",
    value: "往年多在11月初（如2025年为11月1日—11月7日），2026年待公告确认",
    reviewStatus: "historical",
    sourceName: "2025年杭州市招聘公告",
    sourceType: "historical",
    sourceExcerpt: "2025年报名时间为11月1日9时—11月7日16时。",
    scope: ET001_SCOPE,
    updatedAt: "2026-09-25T08:00:00Z",
    version: 1,
  },
  // —— 以下为“考情审核后台”模块的待审核演示种子 ——
  // 模拟学生提交 2026 年公告后 AI 提取、等待人工审核的状态。
  {
    id: "ev-seed-101",
    examTargetId: "et-001",
    field: "registration_time",
    value: "2026年11月1日9时—11月7日16时",
    reviewStatus: "pending_review",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "报名时间：2026年11月1日9时—11月7日16时，通过网上报名系统注册报名。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:00:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  {
    id: "ev-seed-102",
    examTargetId: "et-001",
    field: "exam_time",
    value: "2026年12月13日",
    reviewStatus: "pending_review",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "笔试时间：笔试定于2026年12月13日举行，具体时间和地点以准考证为准。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:00:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  // 分值：两个来源结论不一致 → 来源冲突队列
  {
    id: "ev-seed-103",
    examTargetId: "et-001",
    field: "score",
    value: "两科满分各100分，总分200分",
    reviewStatus: "pending_review",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "笔试科目……两科满分各100分，总分200分。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:05:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  {
    id: "ev-seed-104",
    examTargetId: "et-001",
    field: "score",
    value: "《学科专业知识》单科满分150分，总分300分",
    reviewStatus: "ai_extracted",
    sourceName: "浙江教师招聘信息网（转载）",
    sourceType: "announcement_url",
    sourceUrl: "https://www.zj-jobs-demo.example.com/2026/hangzhou-teacher",
    sourceExcerpt: "据转载消息，学科专业知识满分150分，两科合计300分。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:06:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
  // 低影响字段：资源审核员也可以审核的示例
  {
    id: "ev-seed-105",
    examTargetId: "et-001",
    field: "education_level",
    value: "初中",
    reviewStatus: "ai_extracted",
    sourceName: "杭州市教育局官网",
    sourceType: "announcement_url",
    sourceUrl: ET001_URL,
    sourceExcerpt: "公开招聘初中语文教师12名。",
    scope: ET001_SCOPE,
    updatedAt: "2026-10-01T09:07:00Z",
    jobId: "job-seed-demo",
    version: 1,
  },
];

/** 提交公告表单“填入示例公告”按钮使用的示例文本（含时间/科目/分值/资格条件） */
export const SAMPLE_ANNOUNCEMENT_TEXT = `杭州市教育局2026年上半年公开招聘中小学教师公告
一、招聘岗位：面向社会公开招聘初中语文教师12名。
二、报名时间：2026年11月1日9时—11月7日16时，通过网上报名系统注册报名。
三、笔试时间：笔试定于2026年12月13日举行，具体时间和地点以准考证为准。
四、笔试科目：《教育综合知识》和《学科专业知识（初中语文）》，两科满分各100分，总分200分。
五、报考条件：本科及以上学历；须持有初中及以上语文教师资格证；年龄35周岁以下（1990年11月以后出生）；杭州市户籍优先。
六、考试范围：学科专业知识考查现代汉语、古代汉语、文学常识、语文课程标准与教学设计、写作。`;

// ==================== 用户资料 ====================

// 资料模块演示种子：
// - et-001：一套适用（杭州·初中）
// - et-demo-mat-multi：三套资料冲突（浙江新版 / 全国旧版 / 来源不明扫描件）
// - et-demo-mat-none：不放任何资料，用于“无资料 + 最小资料类别”案例
export const mockMaterials: MaterialItem[] = [
  {
    id: "um-001",
    userId: "u-001",
    examTargetId: "et-001",
    name: "《语文考编通关宝典（浙江专版·初中）》",
    sourceType: "published",
    author: "王某某",
    publisher: "教育出版社",
    applicableRegion: "浙江省",
    year: 2025,
    applicableLevel: "middle",
    coversModules: ["mod_xiandai", "mod_gudai", "mod_wenxue", "mod_jiaoxue", "mod_xiezuo"],
    chapters: [
      { id: "c-001", materialId: "um-001", title: "现代汉语基础", order: 1, isCompleted: true, completedAt: "2026-09-28" },
      { id: "c-002", materialId: "um-001", title: "古代汉语", order: 2, isCompleted: true, completedAt: "2026-09-30" },
      { id: "c-003", materialId: "um-001", title: "文学常识", order: 3, isCompleted: false },
      { id: "c-004", materialId: "um-001", title: "教学设计", order: 4, isCompleted: false },
      { id: "c-005", materialId: "um-001", title: "写作与案例", order: 5, isCompleted: false },
    ],
    catalogConfirmed: true,
    progress: 40,
    note: "学姐推荐的浙江专版，目录已对照2026考纲核对过。",
    createdAt: "2026-09-25T08:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
    status: "in_use",
  },
  {
    id: "um-201",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    name: "《浙江省教师招聘考试·语文学科专业知识（2026 浙江专版）》",
    sourceType: "published",
    author: "浙江省教师招聘考试研究组",
    publisher: "浙江教育出版社",
    applicableRegion: "浙江省",
    year: 2026,
    applicableLevel: "middle",
    coversModules: ["mod_xiandai", "mod_gudai", "mod_wenxue", "mod_kebiao", "mod_jiaoxue", "mod_xiezuo"],
    chapters: [
      { id: "c-201-1", materialId: "um-201", title: "现代汉语基础", order: 1, isCompleted: false },
      { id: "c-201-2", materialId: "um-201", title: "古代汉语", order: 2, isCompleted: false },
      { id: "c-201-3", materialId: "um-201", title: "文学常识与作品分析", order: 3, isCompleted: false },
      { id: "c-201-4", materialId: "um-201", title: "语文课程标准解读", order: 4, isCompleted: false },
      { id: "c-201-5", materialId: "um-201", title: "教学设计", order: 5, isCompleted: false },
      { id: "c-201-6", materialId: "um-201", title: "写作与案例分析", order: 6, isCompleted: false },
    ],
    catalogConfirmed: true,
    progress: 35,
    note: "官网购入的新版，浙江专版。",
    createdAt: "2026-09-23T08:00:00Z",
    updatedAt: "2026-09-28T08:00:00Z",
  },
  {
    id: "um-202",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    name: "《教师招聘语文一本通（全国通用版）》",
    sourceType: "institution",
    author: "某培训机构",
    publisher: "培训机构内部发行",
    applicableRegion: "全国",
    year: 2022,
    applicableLevel: "unknown",
    coversModules: ["mod_xiandai", "mod_wenxue", "mod_xiezuo", "mod_zhenti"],
    chapters: [
      { id: "c-202-1", materialId: "um-202", title: "现代汉语考点速记", order: 1, isCompleted: true },
      { id: "c-202-2", materialId: "um-202", title: "文学常识汇编", order: 2, isCompleted: true },
      { id: "c-202-3", materialId: "um-202", title: "写作模板", order: 3, isCompleted: false },
      { id: "c-202-4", materialId: "um-202", title: "全国教师招聘真题选编", order: 4, isCompleted: false },
    ],
    catalogConfirmed: true,
    progress: 60,
    note: "去年备考买的通用版，做了一大半，不确定浙江是否适用。",
    createdAt: "2025-06-10T08:00:00Z",
    updatedAt: "2026-09-15T08:00:00Z",
  },
  {
    id: "um-203",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    name: "《XX机构内部押题资料·语文（完整扫描版）》",
    sourceType: "unknown_scan",
    applicableRegion: "",
    year: 2025,
    applicableLevel: "unknown",
    coversModules: ["mod_jiaoxue", "mod_zhenti", "mod_lianxi"],
    chapters: [
      { id: "c-203-1", materialId: "um-203", title: "教学设计押题十套", order: 1, isCompleted: false },
      { id: "c-203-2", materialId: "um-203", title: "押题卷与参考答案", order: 2, isCompleted: false },
    ],
    catalogConfirmed: false,
    progress: 10,
    note: "网上群里转来的扫描版，没有出版社信息，不知道能不能用。",
    createdAt: "2026-09-26T08:00:00Z",
    updatedAt: "2026-09-26T08:00:00Z",
  },
];

// ==================== 能力基线 ====================

export const mockAbilityBaselines: AbilityBaseline[] = [
  {
    id: "ab-et-001",
    userId: "u-001",
    examTargetId: "et-001",
    inventoryStatus: "single",
    chineseAssessments: [
      { module: "mod_xiandai", level: 3, note: "语法体系基本过完" },
      { module: "mod_gudai", level: 2, note: "虚词和句式经常错" },
      { module: "mod_wenxue", level: 4 },
      { module: "mod_jiaoxue", level: 2, note: "还没开始练" },
      { module: "mod_xiezuo", level: 3 },
    ],
    generalAssessments: [
      { module: "mod_jiaoyuxue", level: 3 },
      { module: "mod_xinlixue", level: 3 },
      { module: "mod_fagui", level: 2 },
    ],
    recentScores: [
      { id: "ps-001", module: "mod_xiandai", scoreText: "72/100", scorePercent: 72, takenAt: "2026-09-27" },
      { id: "ps-002", module: "mod_gudai", scoreText: "55/100", scorePercent: 55, takenAt: "2026-09-29" },
    ],
    weakModules: ["mod_gudai", "mod_jiaoxue"],
    dailyAvailableMinutes: 180,
    weeklyAvailableHours: 12,
    updatedAt: "2026-09-30T12:00:00Z",
  },
  {
    id: "ab-et-demo-mat-multi",
    userId: "u-001",
    examTargetId: "et-demo-mat-multi",
    inventoryStatus: "multiple",
    chineseAssessments: [
      { module: "mod_xiandai", level: 3 },
      { module: "mod_wenxue", level: 3 },
      { module: "mod_jiaoxue", level: 2, note: "几套资料里都有教学设计，不知道跟哪套" },
    ],
    generalAssessments: [],
    recentScores: [],
    weakModules: ["mod_jiaoxue"],
    dailyAvailableMinutes: 120,
    weeklyAvailableHours: 12,
    updatedAt: "2026-09-28T12:00:00Z",
  },
  {
    id: "ab-et-demo-mat-none",
    userId: "u-001",
    examTargetId: "et-demo-mat-none",
    inventoryStatus: "none",
    chineseAssessments: [],
    generalAssessments: [],
    recentScores: [],
    weakModules: [],
    dailyAvailableMinutes: 90,
    weeklyAvailableHours: 8,
    updatedAt: "2026-09-20T12:00:00Z",
  },
];

/** 首次进入时需要由规则层生成诊断快照的演示目标（无资料案例不在其中） */
export const SEEDED_DIAGNOSIS_TARGET_IDS = ["et-001", "et-demo-mat-multi"];

// ==================== 公共资源 ====================

export const mockPublicResources: PublicResource[] = [
  {
    id: "pr-001",
    title: "《义务教育语文课程标准（2022年版）》",
    description: "教育部发布的最新版语文课程标准，是所有语文教师编考试的必学内容。",
    type: "official",
    source: "中华人民共和国教育部",
    sourceUrl: "http://www.moe.gov.cn/srcsite/A26/s8001/202204/t20220420_619921.html",
    license: "open",
    applicableRegions: ["全国"],
    applicableTypes: ["public_school", "public_institution", "special_teacher"],
    applicableLevels: ["primary", "middle", "high"],
    modules: ["语文课程标准解读"],
    isVerified: true,
    verifiedBy: "审核员A",
    verifiedAt: "2026-09-20T08:00:00Z",
    isActive: true,
    createdAt: "2026-09-20T08:00:00Z",
    updatedAt: "2026-09-20T08:00:00Z",
  },
  {
    id: "pr-002",
    title: "浙江省教师招聘考试历年真题解析",
    description: "收录2020-2025年浙江省各地教师招聘语文科目真题及详细解析。",
    type: "third_party",
    source: "浙江教育考试网",
    sourceUrl: "https://www.zjzs.net",
    license: "restricted",
    applicableRegions: ["浙江省"],
    applicableTypes: ["public_school", "public_institution"],
    applicableLevels: ["primary", "middle", "high"],
    modules: ["真题练习", "浙江教招真题"],
    isVerified: true,
    verifiedBy: "审核员B",
    verifiedAt: "2026-09-25T08:00:00Z",
    isActive: true,
    createdAt: "2026-09-22T08:00:00Z",
    updatedAt: "2026-09-25T08:00:00Z",
  },
  {
    id: "pr-003",
    title: "现代汉语语法知识点精讲",
    description: "系统梳理现代汉语语法知识体系，包含大量练习题。",
    type: "self_made",
    source: "本平台自制",
    sourceUrl: "/resources/modern-chinese-grammar",
    license: "free",
    applicableRegions: ["全国"],
    applicableTypes: ["public_school", "private_school", "public_institution", "special_teacher"],
    applicableLevels: ["primary", "middle", "high"],
    modules: ["现代汉语基础"],
    isVerified: true,
    verifiedBy: "审核员A",
    verifiedAt: "2026-09-15T08:00:00Z",
    isActive: true,
    createdAt: "2026-09-15T08:00:00Z",
    updatedAt: "2026-09-15T08:00:00Z",
  },
  {
    id: "pr-004",
    title: "教学设计万能模板与案例库",
    description: "涵盖小学、初中、高中各学段的教学设计模板和优秀案例。",
    type: "self_made",
    source: "本平台自制",
    sourceUrl: "/resources/teaching-design",
    license: "free",
    applicableRegions: ["全国"],
    applicableTypes: ["public_school", "private_school"],
    applicableLevels: ["primary", "middle", "high"],
    modules: ["教学设计", "教材分析"],
    isVerified: true,
    verifiedBy: "审核员B",
    verifiedAt: "2026-09-18T08:00:00Z",
    isActive: true,
    createdAt: "2026-09-18T08:00:00Z",
    updatedAt: "2026-09-18T08:00:00Z",
  },
];

// ==================== 本周计划 ====================

export const mockWeeklyPlan: WeeklyPlan = {
  id: "wp-001",
  userId: "u-001",
  examTargetId: "et-001",
  weekNumber: 1,
  startDate: "2026-09-28",
  endDate: "2026-10-04",
  focus: "夯实语文基础知识：现代汉语语法 + 古代汉语虚词 + 文学常识积累",
  status: "active",
  version: 1,
  createdAt: "2026-09-28T08:00:00Z",
  updatedAt: "2026-10-01T08:00:00Z",
};

// ==================== 每日计划 ====================

export const mockDailyPlans: DailyPlan[] = [
  {
    id: "dp-001",
    weeklyPlanId: "wp-001",
    date: "2026-09-28",
    dayOfWeek: 1,
    tasks: [
      {
        id: "t-001",
        dailyPlanId: "dp-001",
        title: "现代汉语语法：词类辨析练习",
        module: "现代汉语基础",
        materialId: "um-001",
        materialChapterId: "c-001",
        estimatedTime: 60,
        completionCriteria: "完成《通关宝典》第1章课后练习，正确率80%以上",
        order: 1,
        status: "completed",
        isCore: true,
        feedback: {
          id: "tf-001",
          taskId: "t-001",
          userId: "u-001",
          status: "completed",
          actualTime: 75,
          errorTypes: ["careless"],
          hasSecondPractice: true,
          notes: "副词和介词的区分还需要加强",
          createdAt: "2026-09-28T21:00:00Z",
        },
        createdAt: "2026-09-28T08:00:00Z",
        updatedAt: "2026-09-28T21:00:00Z",
      },
      {
        id: "t-002",
        dailyPlanId: "dp-001",
        title: "古代汉语：虚词之、其、而用法总结",
        module: "古代汉语",
        materialId: "um-001",
        materialChapterId: "c-002",
        estimatedTime: 45,
        completionCriteria: "整理常见虚词用法表格，完成10道虚词辨析题",
        order: 2,
        status: "completed",
        isCore: true,
        feedback: {
          id: "tf-002",
          taskId: "t-002",
          userId: "u-001",
          status: "completed",
          actualTime: 50,
          errorTypes: [],
          hasSecondPractice: false,
          createdAt: "2026-09-28T21:00:00Z",
        },
        createdAt: "2026-09-28T08:00:00Z",
        updatedAt: "2026-09-28T21:00:00Z",
      },
    ],
    totalEstimatedTime: 105,
    isMinimumViable: false,
    createdAt: "2026-09-28T08:00:00Z",
    updatedAt: "2026-09-28T21:00:00Z",
  },
  {
    id: "dp-002",
    weeklyPlanId: "wp-001",
    date: "2026-09-29",
    dayOfWeek: 2,
    tasks: [
      {
        id: "t-003",
        dailyPlanId: "dp-002",
        title: "现代汉语语法：句子成分分析",
        module: "现代汉语基础",
        materialId: "um-001",
        materialChapterId: "c-001",
        estimatedTime: 60,
        completionCriteria: "能准确划分主谓宾定状补，完成20道分析题",
        order: 1,
        status: "completed",
        isCore: true,
        feedback: {
          id: "tf-003",
          taskId: "t-003",
          userId: "u-001",
          status: "partial",
          actualTime: 60,
          incompleteReason: "difficulty",
          errorTypes: ["misunderstanding"],
          hasSecondPractice: false,
          notes: "复杂句式的层次分析有困难",
          createdAt: "2026-09-29T21:00:00Z",
        },
        createdAt: "2026-09-29T08:00:00Z",
        updatedAt: "2026-09-29T21:00:00Z",
      },
      {
        id: "t-004",
        dailyPlanId: "dp-002",
        title: "文学常识：唐宋八大家作品梳理",
        module: "文学常识",
        materialId: "um-001",
        materialChapterId: "c-003",
        estimatedTime: 40,
        completionCriteria: "记住八大家姓名、代表作和艺术特色",
        order: 2,
        status: "completed",
        isCore: true,
        feedback: {
          id: "tf-004",
          taskId: "t-004",
          userId: "u-001",
          status: "completed",
          actualTime: 35,
          errorTypes: [],
          hasSecondPractice: false,
          createdAt: "2026-09-29T21:00:00Z",
        },
        createdAt: "2026-09-29T08:00:00Z",
        updatedAt: "2026-09-29T21:00:00Z",
      },
    ],
    totalEstimatedTime: 100,
    isMinimumViable: false,
    createdAt: "2026-09-29T08:00:00Z",
    updatedAt: "2026-09-29T21:00:00Z",
  },
  {
    id: "dp-003",
    weeklyPlanId: "wp-001",
    date: "2026-09-30",
    dayOfWeek: 3,
    tasks: [
      {
        id: "t-005",
        dailyPlanId: "dp-003",
        title: "古代汉语：实词词类活用归纳",
        module: "古代汉语",
        materialId: "um-001",
        materialChapterId: "c-002",
        estimatedTime: 50,
        completionCriteria: "归纳名词、动词、形容词活用规律各5例",
        order: 1,
        status: "completed",
        isCore: true,
        feedback: {
          id: "tf-005",
          taskId: "t-005",
          userId: "u-001",
          status: "completed",
          actualTime: 55,
          errorTypes: ["knowledge_gap"],
          hasSecondPractice: true,
          notes: "意动用法和使动用法的区分需要再练",
          createdAt: "2026-09-30T21:00:00Z",
        },
        createdAt: "2026-09-30T08:00:00Z",
        updatedAt: "2026-09-30T21:00:00Z",
      },
      {
        id: "t-006",
        dailyPlanId: "dp-003",
        title: "文学常识：诗词鉴赏基本方法",
        module: "文学常识",
        materialId: "um-001",
        materialChapterId: "c-003",
        estimatedTime: 45,
        completionCriteria: "掌握意象、意境、手法、情感四步分析法",
        order: 2,
        status: "completed",
        isCore: true,
        feedback: {
          id: "tf-006",
          taskId: "t-006",
          userId: "u-001",
          status: "completed",
          actualTime: 40,
          errorTypes: [],
          hasSecondPractice: false,
          createdAt: "2026-09-30T21:00:00Z",
        },
        createdAt: "2026-09-30T08:00:00Z",
        updatedAt: "2026-09-30T21:00:00Z",
      },
    ],
    totalEstimatedTime: 95,
    isMinimumViable: false,
    createdAt: "2026-09-30T08:00:00Z",
    updatedAt: "2026-09-30T21:00:00Z",
  },
  {
    id: "dp-004",
    weeklyPlanId: "wp-001",
    date: "2026-10-01",
    dayOfWeek: 4,
    tasks: [
      {
        id: "t-007",
        dailyPlanId: "dp-004",
        title: "现代汉语：病句辨析专项训练",
        module: "现代汉语基础",
        materialId: "um-001",
        materialChapterId: "c-001",
        estimatedTime: 50,
        completionCriteria: "完成30道病句题，正确率75%以上",
        order: 1,
        status: "in_progress",
        isCore: true,
        createdAt: "2026-10-01T08:00:00Z",
        updatedAt: "2026-10-01T08:00:00Z",
      },
      {
        id: "t-008",
        dailyPlanId: "dp-004",
        title: "古代汉语：特殊句式（判断、被动、倒装）",
        module: "古代汉语",
        materialId: "um-001",
        materialChapterId: "c-002",
        estimatedTime: 45,
        completionCriteria: "能识别并翻译三种特殊句式各5例",
        order: 2,
        status: "pending",
        isCore: true,
        createdAt: "2026-10-01T08:00:00Z",
        updatedAt: "2026-10-01T08:00:00Z",
      },
      {
        id: "t-009",
        dailyPlanId: "dp-004",
        title: "语文课程标准导读",
        module: "课程标准",
        estimatedTime: 30,
        completionCriteria: "了解课程性质、基本理念和设计思路",
        order: 3,
        status: "pending",
        isCore: false,
        createdAt: "2026-10-01T08:00:00Z",
        updatedAt: "2026-10-01T08:00:00Z",
      },
    ],
    totalEstimatedTime: 125,
    isMinimumViable: false,
    adjustmentNote: "今天是国庆假期第一天，如果学习时间不足，优先完成核心任务（病句辨析）",
    createdAt: "2026-10-01T08:00:00Z",
    updatedAt: "2026-10-01T08:00:00Z",
  },
  {
    id: "dp-005",
    weeklyPlanId: "wp-001",
    date: "2026-10-02",
    dayOfWeek: 5,
    tasks: [
      {
        id: "t-010",
        dailyPlanId: "dp-005",
        title: "文学常识：现当代文学名家名作",
        module: "文学常识",
        materialId: "um-001",
        materialChapterId: "c-003",
        estimatedTime: 50,
        completionCriteria: "整理鲁迅、茅盾、巴金、老舍代表作清单",
        order: 1,
        status: "pending",
        isCore: true,
        createdAt: "2026-10-02T08:00:00Z",
        updatedAt: "2026-10-02T08:00:00Z",
      },
      {
        id: "t-011",
        dailyPlanId: "dp-005",
        title: "教育综合：教育学基础概念",
        module: "教育综合知识",
        materialId: "um-002",
        materialChapterId: "c-006",
        estimatedTime: 40,
        completionCriteria: "理解教育、教育学、教育功能等基本概念",
        order: 2,
        status: "pending",
        isCore: true,
        createdAt: "2026-10-02T08:00:00Z",
        updatedAt: "2026-10-02T08:00:00Z",
      },
    ],
    totalEstimatedTime: 90,
    isMinimumViable: false,
    createdAt: "2026-10-02T08:00:00Z",
    updatedAt: "2026-10-02T08:00:00Z",
  },
  {
    id: "dp-006",
    weeklyPlanId: "wp-001",
    date: "2026-10-03",
    dayOfWeek: 6,
    tasks: [
      {
        id: "t-012",
        dailyPlanId: "dp-006",
        title: "综合练习：语文基础知识模拟测试",
        module: "综合练习",
        estimatedTime: 60,
        completionCriteria: "完成50道选择题，记录错题并分析原因",
        order: 1,
        status: "pending",
        isCore: true,
        createdAt: "2026-10-03T08:00:00Z",
        updatedAt: "2026-10-03T08:00:00Z",
      },
      {
        id: "t-013",
        dailyPlanId: "dp-006",
        title: "错题回顾与薄弱点分析",
        module: "错题分析",
        estimatedTime: 30,
        completionCriteria: "整理本周错题，标出错因类型",
        order: 2,
        status: "pending",
        isCore: true,
        createdAt: "2026-10-03T08:00:00Z",
        updatedAt: "2026-10-03T08:00:00Z",
      },
    ],
    totalEstimatedTime: 90,
    isMinimumViable: false,
    createdAt: "2026-10-03T08:00:00Z",
    updatedAt: "2026-10-03T08:00:00Z",
  },
  {
    id: "dp-007",
    weeklyPlanId: "wp-001",
    date: "2026-10-04",
    dayOfWeek: 7,
    tasks: [
      {
        id: "t-014",
        dailyPlanId: "dp-007",
        title: "本周复盘：知识掌握情况自测",
        module: "周复盘",
        estimatedTime: 40,
        completionCriteria: "完成本周学习内容自评表",
        order: 1,
        status: "pending",
        isCore: true,
        createdAt: "2026-10-04T08:00:00Z",
        updatedAt: "2026-10-04T08:00:00Z",
      },
      {
        id: "t-015",
        dailyPlanId: "dp-007",
        title: "下周计划预览与调整",
        module: "计划调整",
        estimatedTime: 20,
        completionCriteria: "确认下周学习重点和可用时间",
        order: 2,
        status: "pending",
        isCore: true,
        createdAt: "2026-10-04T08:00:00Z",
        updatedAt: "2026-10-04T08:00:00Z",
      },
    ],
    totalEstimatedTime: 60,
    isMinimumViable: true,
    createdAt: "2026-10-04T08:00:00Z",
    updatedAt: "2026-10-04T08:00:00Z",
  },
];

// ==================== 用户设置 ====================

export const mockUserSettings: UserSettings = {
  educationLevel: "middle",
  dailyAvailableTime: 180,
  studyReminderTime: "08:00",
  notifications: {
    studyReminder: true,
    examUpdate: true,
    resourceUpdate: true,
    weeklyReport: true,
  },
};

// ==================== 本地存储键名 ====================

export const STORAGE_KEYS = {
  SESSION: "kb_session",
  USER: "kb_user",
  EXAM_TARGETS: "kb_exam_targets",
  EVIDENCE_ITEMS: "kb_evidence_items",
  EXTRACTION_JOBS: "kb_extraction_jobs",
  CORRECTIONS: "kb_corrections",
  REVIEW_LOGS: "kb_review_logs",
  MATERIALS: "kb_materials",
  ABILITY_BASELINES: "kb_ability_baselines",
  MATERIAL_DIAGNOSES: "kb_material_diagnoses",
  RESOURCES: "kb_public_resources",
  PLANS: "kb_plans",
  SETTINGS: "kb_settings",
} as const;
